# Указываем базовый образ Node.js
FROM node:18

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY ./server/package*.json ./
RUN npm install

# Копируем остальные файлы проекта
COPY ./server .

# Экспонируем порт 5000
EXPOSE 5000

# Указываем команду для запуска приложения
CMD ["npm", "start"]
